In [10]:
import pandas as pd

df = pd.read_csv(r"dataset\amazon_reviews_cleaned.csv", nrows=5)
df

,category,asin,reviewText,summary,overall,verified,vote,unixReviewTime,sentiment,text,clean_text
0,Cell Phones and Accessories,7508492919,Looks even better in person. Be careful to not...,Can't stop won't stop looking at it,5.0,True,NaN,1407110400,positive,Can't stop won't stop looking at it Looks even...,cant stop wont stop looking at it looks even b...
1,Cell Phones and Accessories,7508492919,When you don't want to spend a whole lot of ca...,1,5.0,True,NaN,1392163200,positive,1 When you don't want to spend a whole lot of ...,1 when you dont want to spend a whole lot of c...
2,Cell Phones and Accessories,7508492919,"so the case came on time, i love the design. I...",Its okay,3.0,True,NaN,1391817600,neutral,"Its okay so the case came on time, i love the ...",its okay so the case came on time i love the d...
3,Cell Phones and Accessories,7508492919,DON'T CARE FOR IT. GAVE IT AS A GIFT AND THEY...,CASE,2.0,True,NaN,1391472000,negative,CASE DON'T CARE FOR IT. GAVE IT AS A GIFT AND...,case dont care for it gave it as a gift and th...
4,Cell Phones and Accessories,7508492919,"I liked it because it was cute, but the studs ...",Cute!,4.0,True,NaN,1391385600,positive,"Cute! I liked it because it was cute, but the ...",cute i liked it because it was cute but the st...

In [11]:
df[["category", "overall", "sentiment", "text", "clean_text"]].head()

,category,overall,sentiment,text,clean_text
0,Cell Phones and Accessories,5.0,positive,Can't stop won't stop looking at it Looks even...,cant stop wont stop looking at it looks even b...
1,Cell Phones and Accessories,5.0,positive,1 When you don't want to spend a whole lot of ...,1 when you dont want to spend a whole lot of c...
2,Cell Phones and Accessories,3.0,neutral,"Its okay so the case came on time, i love the ...",its okay so the case came on time i love the d...
3,Cell Phones and Accessories,2.0,negative,CASE DON'T CARE FOR IT. GAVE IT AS A GIFT AND...,case dont care for it gave it as a gift and th...
4,Cell Phones and Accessories,4.0,positive,"Cute! I liked it because it was cute, but the ...",cute i liked it because it was cute but the st...

In [13]:

df = pd.read_csv(r"dataset\amazon_reviews_cleaned.csv")

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nMissing values:")
print(df.isnull().sum())

print("\nCategory counts:")
print(df["category"].value_counts())

print("\nSentiment counts:")
print(df["sentiment"].value_counts())

print("\nEmpty clean_text rows:")
print((df["clean_text"].str.strip() == "").sum())

C:\Users\linnu\AppData\Local\Temp\ipykernel_23752\2130228707.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"dataset\amazon_reviews_cleaned.csv")

Shape: (4045448, 11)

Columns:
['category', 'asin', 'reviewText', 'summary', 'overall', 'verified', 'vote', 'unixReviewTime', 'sentiment', 'text', 'clean_text']

Missing values:
category                0
asin                    0
reviewText           2022
summary              1180
overall                 0
verified                0
vote              3564914
unixReviewTime          0
sentiment               0
text                  130
clean_text            234
dtype: int64

Category counts:
category
Sports and Outdoors            2839940
Cell Phones and Accessories    1128437
Industrial and Scientific        77071
Name: count, dtype: int64

Sentiment counts:
sentiment
positive    3376611
negative     355926
neutral      312911
Name: count, dtype: int64

Empty clean_text rows:
0

In [14]:
df = df.dropna(subset=["overall", "sentiment", "text", "clean_text"])
df = df[df["clean_text"].str.strip() != ""]
df = df.drop_duplicates(subset=["category", "asin", "clean_text"])

print("New shape after cleaning:", df.shape)

New shape after cleaning: (3849347, 11)

In [15]:
pd.crosstab(df["category"], df["sentiment"])

sentiment                    negative  neutral  positive
category
Cell Phones and Accessories    138024    97704    872207
Industrial and Scientific        4152     4184     63968
Sports and Outdoors            201574   198831   2268703

In [16]:
sample_size = 40000

cell_df = df[df["category"] == "Cell Phones and Accessories"].sample(n=sample_size, random_state=42)
sports_df = df[df["category"] == "Sports and Outdoors"].sample(n=sample_size, random_state=42)
industrial_df = df[df["category"] == "Industrial and Scientific"].sample(n=min(sample_size, len(df[df["category"] == "Industrial and Scientific"])), random_state=42)

balanced_df = pd.concat([cell_df, sports_df, industrial_df], ignore_index=True)

print(balanced_df["category"].value_counts())

category
Cell Phones and Accessories    40000
Sports and Outdoors            40000
Industrial and Scientific      40000
Name: count, dtype: int64

In [17]:
df[["category", "overall", "sentiment", "text", "clean_text"]].head()

,category,overall,sentiment,text,clean_text
0,Cell Phones and Accessories,5.0,positive,Can't stop won't stop looking at it Looks even...,cant stop wont stop looking at it looks even b...
1,Cell Phones and Accessories,5.0,positive,1 When you don't want to spend a whole lot of ...,1 when you dont want to spend a whole lot of c...
2,Cell Phones and Accessories,3.0,neutral,"Its okay so the case came on time, i love the ...",its okay so the case came on time i love the d...
3,Cell Phones and Accessories,2.0,negative,CASE DON'T CARE FOR IT. GAVE IT AS A GIFT AND...,case dont care for it gave it as a gift and th...
4,Cell Phones and Accessories,4.0,positive,"Cute! I liked it because it was cute, but the ...",cute i liked it because it was cute but the st...